/**
 * Derives the CSP `script-src` hashes for the inline scripts in `index.html`.
 *
 *   node scripts/csp-hashes.mjs        # rewrites src/csp-hashes.ts
 *
 * The theme bootstrap in `index.html` has to run before the first paint, so it
 * cannot move into a module the bundler defers. `'unsafe-inline'` would buy that
 * one script at the price of every injected script, so the Worker names the exact
 * script by hash instead. Hand-copying a hash is how it goes stale, hence this
 * generator: `pnpm --filter web build` runs it first, and `tests/csp.test.mjs`
 * fails if the committed module ever drifts from `index.html`.
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

/** Types the browser executes. Anything else (JSON, importmap data, templates) carries no hash. */
const executable = /^(?:|module|text\/javascript|application\/javascript)$/i;

/**
 * Every inline `<script>` in the document, in source order, as CSP hash sources.
 * The digest covers the element's text content exactly as written, which is what
 * the browser hashes.
 */
export function inlineScriptHashes(html) {
  const hashes = [];
  const tags = /<script\b([^>]*)>([\s\S]*?)<\/script\s*>/gi;
  for (const [, attributes, body] of html.matchAll(tags)) {
    if (/\bsrc\s*=/i.test(attributes)) continue;
    const type = attributes.match(/\btype\s*=\s*["']?([^"'\s>]*)/i)?.[1] ?? "";
    if (!executable.test(type)) continue;
    hashes.push("sha256-" + createHash("sha256").update(body, "utf8").digest("base64"));
  }
  return hashes;
}

/** The committed module the Worker imports; regenerating on a clean tree is a no-op. */
export function renderModule(hashes) {
  return `/**
 * Generated by \`scripts/csp-hashes.mjs\` from the inline scripts in \`index.html\`.
 * Do not edit: run \`pnpm --filter web csp:hashes\` (or any \`build\`) instead.
 */
export const inlineScriptHashes = [
${hashes.map(hash => `  "${hash}",\n`).join("")}] as const;
`;
}

export const htmlFile = new URL("../index.html", import.meta.url);
export const moduleFile = new URL("../src/csp-hashes.ts", import.meta.url);

/** The hashes the committed HTML implies, for the generator and for the drift test. */
export function currentHashes() {
  return inlineScriptHashes(readFileSync(htmlFile, "utf8"));
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const hashes = currentHashes();
  writeFileSync(fileURLToPath(moduleFile), renderModule(hashes));
  console.log(`CSP script hashes: ${hashes.length} inline script(s) -> src/csp-hashes.ts`);
}
