/**
 * Generated by `scripts/csp-hashes.mjs` from the inline scripts in `index.html`.
 * Do not edit: run `pnpm --filter web csp:hashes` (or any `build`) instead.
 */
export const inlineScriptHashes = [
  "sha256-9ExV37QZ0hSf5hnF/xfLQkFsY0losYz3E0rxZmo6i7Q=",
] as const;
