import { compileTheme } from "@xp/theme";
import { fontOption, fontRoles, fontStylesheets, themeSpec, type ConfiguratorState } from "./config";
import { canonical } from "./serialize";

/** Kept beside the CSS writer so the exported file and the running app cannot drift. */
export const contentMaxWidth = { reading: "var(--measure-body)", wide: "var(--measure-wide)", full: "none" } as const;

export const rootAttributes = (state: ConfiguratorState) => ({
  "data-xp-sidebar": state.layout.sidebar,
  "data-xp-content": state.layout.content,
  "data-xp-rail": state.layout.rail,
  "data-xp-motion": state.layout.motion,
});

export function exportCss(state: ConfiguratorState): string {
  const imports = fontStylesheets(state).map(href => `@import url("${href}");`);
  const attributes = Object.entries(rootAttributes(state)).map(([name, value]) => `${name}="${value}"`).join(" ");
  const header = [
    "/* Generated by the xpresso configurator (/configure).",
    " * Load this after @xp/core and the component stylesheets, in place of @xp/theme/theme.css.",
    " * Copy apps/web/public/fonts/*.woff2 into your public/fonts/ for registered local faces.",
    ` * Layout switches live on the html element: <html ${attributes}>`,
    " */",
  ].join("\n");
  const layout = `:root {\n  --xp-content-max: ${contentMaxWidth[state.layout.content]};\n}`;
  return [...imports, header, compileTheme(themeSpec(state)).trim(), layout, ""].join("\n");
}

export function exportJson(state: ConfiguratorState): string {
  return JSON.stringify(canonical({ v: 1, ...state }), null, 2) + "\n";
}

/**
 * A drop-in module, not a fragment: it compiles on its own, names its own types, carries the
 * stylesheets the chosen families need, and exposes the one call that applies all of it. Naming a
 * family without loading its faces would hand over a configuration that silently falls back to
 * the system font, so the loader and the apply path ship with the spec.
 */
export function exportConfigSnippet(state: ConfiguratorState): string {
  const stacks = fontRoles.map(role => `    ${role}: ${JSON.stringify(fontOption(role, state.fonts[role]).stack)},`);
  const seeds = Object.entries(state.colors).map(([family, seed]) => `    ${family}: { hue: ${seed.hue}, chroma: ${seed.chroma} },`);
  const stylesheets = fontStylesheets(state);
  const attributes = Object.entries(rootAttributes(state)).map(([name, value]) => `  ${JSON.stringify(name)}: ${JSON.stringify(value)},`);
  return [
    "// xpresso.config.ts — generated by the configurator at /configure",
    '// Apply it once, before or after your first render: applyConfiguration().',
    '// Copy apps/web/public/fonts/*.woff2 into your public/fonts/ for registered local faces.',
    'import { applyTheme, setThemePreference, type ThemeSpec } from "@xp/theme";',
    "",
    "export const theme: ThemeSpec = {",
    "  fonts: {",
    ...stacks,
    `    webfonts: ${JSON.stringify(themeSpec(state).fonts.webfonts)},`,
    "  },",
    "  colors: {",
    ...seeds,
    "  },",
    `  spacingScale: ${state.spacingScale},`,
    `  radiusScale: ${state.radiusScale},`,
    `  shadowScale: ${state.shadowScale},`,
    `  density: ${state.density},`,
    "};",
    "",
    "/** The families above are only names until these faces are registered. */",
    `export const fontStylesheets: readonly string[] = ${JSON.stringify(stylesheets)};`,
    "",
    "export const layout = {",
    `  sidebar: ${JSON.stringify(state.layout.sidebar)},`,
    `  content: ${JSON.stringify(state.layout.content)},`,
    `  rail: ${JSON.stringify(state.layout.rail)},`,
    `  motion: ${JSON.stringify(state.layout.motion)},`,
    "} as const;",
    "",
    "/** The shell reads the layout from these root attributes and this custom property. */",
    "export const rootAttributes: Record<string, string> = {",
    ...attributes,
    "};",
    `export const contentMaxWidth = ${JSON.stringify(contentMaxWidth[state.layout.content])};`,
    "",
    "/** light, dark, or system to follow the reader's operating system. */",
    `export const colorMode = ${JSON.stringify(state.mode)};`,
    "",
    "export function loadFontStylesheets(target: Document = document): void {",
    "  for (const href of fontStylesheets) {",
    '    if (target.querySelector(`link[data-xp-webfont][href="${href}"]`)) continue;',
    '    const link = target.createElement("link");',
    '    link.rel = "stylesheet";',
    "    link.href = href;",
    '    link.dataset.xpWebfont = "";',
    "    target.head.append(link);",
    "  }",
    "}",
    "",
    "/** Fonts first, then the tokens, then the colour mode, then the layout the shell reads. */",
    "export function applyConfiguration(target: Document = document): void {",
    "  loadFontStylesheets(target);",
    "  applyTheme(theme);",
    "  // setThemePreference persists the choice and reflects it on the running document.",
    "  setThemePreference(colorMode);",
    "  for (const [name, value] of Object.entries(rootAttributes)) target.documentElement.setAttribute(name, value);",
    '  target.documentElement.style.setProperty("--xp-content-max", contentMaxWidth);',
    "}",
    "",
    "export default { theme, fontStylesheets, layout, rootAttributes, contentMaxWidth, colorMode, applyConfiguration };",
    "",
  ].join("\n");
}

export const exportFileName = { css: "xpresso-theme.css", json: "xpresso-preset.json", snippet: "xpresso.config.ts" } as const;
