"use client";

import { ChoiceSet, Field, FieldGroup, MorphSlot, StickyActionBar, useDeviceClass, type DeviceClass } from "@xp/primitives";
import { Fragment, useMemo, useRef, useState, type CSSProperties, type FormEvent, type ReactNode } from "react";
import { resolveContactFixture, type ContactAction, type ContactChannel, type ContactFixture, type ContactFormStatus, type ContactMediaRecord, type ContactStressKey, type ResolvedContactFixture } from "./contact-model";

export type ContactScenario={formStatus?:ContactFormStatus;filled?:boolean;servicesSelected?:boolean;mediaFallback?:boolean;proofFallback?:boolean;paused?:boolean};
export type ContactProperties={fixture:ContactFixture;media:ContactMediaRecord[];stress?:ContactStressKey;scenario?:ContactScenario;className?:string};
const ladder:Record<DeviceClass,string>={M:"mobile",TP:"tablet-portrait",TL:"tablet-landscape",DS:"desktop-standard",DW:"desktop-wide"};
const icon:Record<string,string>={clock:"◷",pin:"⌖",phone:"⌕",mail:"↗",chat:"◇"};

const findAction=(model:ResolvedContactFixture,id:string)=>model.actions.find((action)=>action.id===id);
function NativeAction({action,className,children}:{action?:ContactAction;className?:string;children?:ReactNode}){if(!action||action.kind==="submit")return null;return <a className={className} href={action.href} data-action-id={action.id} data-action-kind={action.kind}>{children??action.label}</a>}

function MediaView({model,id,className,forcedFallback=false}:{model:ResolvedContactFixture;id:string;className?:string;forcedFallback?:boolean}){
  const asset=model.mediaById.get(id);if(!asset)return null;const failed=forcedFallback||model.failedMedia;
  if(failed)return <div className={["xp-contact__media","xp-contact__media--fallback",className].filter(Boolean).join(" ")} data-media-seat-id={id} data-media-state="fallback" role="img" aria-label={`${asset.alt}. Image unavailable.`}><span aria-hidden="true">◇</span><strong>Visual record unavailable</strong><small>{asset.alt}</small></div>;
  const src=asset.kind==="avatar"?`${asset.publicBase}.webp`:`${asset.publicBase}-1280.webp`;
  return <figure className={["xp-contact__media",className].filter(Boolean).join(" ")} data-media-seat-id={id} data-media-state="resolved"><img src={src} alt={asset.alt} loading="lazy" decoding="async" style={{objectPosition:asset.focals?.M?.objectPosition}}/></figure>;
}
function VectorView({model,id,forcedFallback=false}:{model:ResolvedContactFixture;id:string;forcedFallback?:boolean}){const asset=model.vectorById.get(id);if(!asset)return null;if(forcedFallback||model.failedMedia)return <span className="xp-contact__vector xp-contact__vector--fallback" data-vector-seat-id={id} role="img" aria-label={`${asset.alt}. Mark unavailable.`}>XP</span>;return <img className="xp-contact__vector" data-vector-seat-id={id} src={asset.src} alt={asset.alt}/>}

function BreakableValue({value}:{value:string}){return <>{value.split(/([@.])/).map((part,index)=><Fragment key={`${part}-${index}`}>{part}{part==="@"||part==="."?<wbr/>:null}</Fragment>)}</>}
function ChannelRow({model,channel}:{model:ResolvedContactFixture;channel:ContactChannel}){return <article className="xp-contact__channel" data-channel-id={channel.id}><span className="xp-contact__channel-icon" aria-hidden="true">{icon[channel.iconKey]??"•"}</span><div><h3>{channel.label}</h3><p><BreakableValue value={channel.value}/></p><div className="xp-contact__channel-actions">{channel.actionIds.map((id)=><NativeAction action={findAction(model,id)} key={id}/>)}</div></div></article>}
function Channels({model,channels=model.channels}:{model:ResolvedContactFixture;channels?:ContactChannel[]}){return channels.length?<div className="xp-contact__channels" data-channel-count={channels.length}>{channels.map((channel)=><ChannelRow model={model} channel={channel} key={channel.id}/>)}</div>:null}

function Directory({model,scenario}:{model:ResolvedContactFixture;scenario?:ContactScenario}){if(!model.offices.length)return null;return <div className="xp-contact__directory" data-directory-mode={model.behavior.compactDirectory} data-office-count={model.offices.length}>{model.offices.map((office)=><article className="xp-contact__office" data-office-id={office.id} key={office.id}>{office.illustrationId?<VectorView model={model} id={office.illustrationId} forcedFallback={scenario?.mediaFallback}/>:null}{office.mediaId?<MediaView model={model} id={office.mediaId} forcedFallback={scenario?.mediaFallback}/>:null}<div className="xp-contact__office-copy"><p className="xp-contact__kicker">Office</p><h2>{office.name}</h2><p>{office.description}</p><Channels model={model} channels={office.channels}/></div></article>)}</div>}

function ContactForm({model,scenario,deviceClass}:{model:ResolvedContactFixture;scenario?:ContactScenario;deviceClass:DeviceClass}){
  const form=model.form!;const forced=model.activeStress==="error"?"error":scenario?.formStatus;const [status,setStatus]=useState<ContactFormStatus>(forced??"idle");const [values,setValues]=useState<Record<string,string>>(()=>Object.fromEntries(form.fields.map((field)=>[field.id,scenario?.filled?field.kind==="email"?"rhea@northstar.example":field.kind==="budget"?"18000":"Ready for review":""])));const [service,setService]=useState(scenario?.servicesSelected?form.services[0]?.value??"":"");const summary=useRef<HTMLDivElement>(null);
  const invalidIds=useMemo(()=>new Set(status==="invalid"||status==="error"?form.fields.filter((field)=>field.required&&!values[field.id]?.trim()).map(({id})=>id):[]),[form.fields,status,values]);
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const missing=form.fields.filter((field)=>field.required&&!values[field.id]?.trim());if(missing.length||(form.services.length&&!service)){setStatus("invalid");requestAnimationFrame(()=>summary.current?.focus());return}setStatus("submitting");globalThis.setTimeout(()=>setStatus("success"),180)};
  const reset=()=>{setValues(Object.fromEntries(form.fields.map(({id})=>[id,""])));setService("");setStatus("idle")};const submitAction=findAction(model,form.submitActionId)!;
  if(status==="success")return <section className="xp-contact__success" aria-live="polite" data-form-state="success"><p className="xp-contact__kicker">Sent securely</p><h2>{form.successTitle}</h2><p>{form.successBody}</p><button type="button" onClick={reset}>Send another enquiry</button></section>;
  return <><form id={`${model.sourceKey}-form`} className="xp-contact__form" noValidate onSubmit={submit} data-form-state={status} data-form-id={form.id}>
    <header><p className="xp-contact__kicker">Start a conversation</p><h2>Tell us what you need</h2></header>
    {(status==="invalid"||status==="error")?<div className="xp-contact__error-summary" ref={summary} tabIndex={-1} role="alert"><strong>{form.errorSummaryTitle}</strong><p>{status==="error"?"The request could not be sent. Your entries are still here.":"Review the marked fields and try again."}</p></div>:null}
    <FieldGroup><legend>Your details</legend><div className="xp-contact__field-grid">{form.fields.map((field)=>{const error=form.fieldErrors.find(({fieldId})=>fieldId===field.id)?.message;const invalid=invalidIds.has(field.id);return <Field id={field.id} invalid={invalid} hasHelp={Boolean(field.help)} hasError={invalid} key={field.id}><Field.Label>{field.label}</Field.Label>{field.kind==="message"?<Field.Textarea name={field.id} required={field.required} maxLength={field.maxLength} placeholder={field.placeholder} value={values[field.id]} onChange={(event)=>{setValues((current)=>({...current,[field.id]:event.target.value}));if(status!=="idle")setStatus("idle")}}/>:<Field.Input name={field.id} type={field.kind==="email"?"email":field.kind==="phone"?"tel":field.kind==="budget"?"number":"text"} required={field.required} maxLength={field.maxLength} placeholder={field.placeholder} autoComplete={field.autocomplete??"off"} inputMode={field.inputMode??"text"} enterKeyHint={field.kind==="email"||field.kind==="phone"?"next":"done"} value={values[field.id]} onChange={(event)=>{setValues((current)=>({...current,[field.id]:event.target.value}));if(status!=="idle")setStatus("idle")}}/>}{field.help?<Field.Help>{field.help}</Field.Help>:null}{invalid?<Field.Error>{error}</Field.Error>:null}</Field>})}</div></FieldGroup>
    {form.services.length?<FieldGroup className="xp-contact__services"><legend>Choose one service</legend><ChoiceSet label="Choose one service" items={form.services.map((choice)=>({value:choice.value,label:choice.label}))} value={service} onChange={(value)=>{setService(value);if(status!=="idle")setStatus("idle")}}/>{(status==="invalid"&&!service)?<p className="xp-contact__service-error" role="alert">Choose a service before sending.</p>:null}</FieldGroup>:null}
    <button className="xp-contact__submit" type="submit" data-action-id={submitAction.id} disabled={status==="submitting"}>{status==="submitting"?form.submittingLabel:submitAction.label}</button>
  </form>{model.behavior.stickySubmitOnTouch&&(deviceClass==="M"||deviceClass==="TP")?<StickyActionBar className="xp-contact__sticky" placement="local" summary="Your enquiry stays in this form." primary={<button type="submit" form={`${model.sourceKey}-form`} data-action-id={submitAction.id} data-submit-request="sticky" disabled={status==="submitting"}>{status==="submitting"?form.submittingLabel:submitAction.label}</button>}/>:null}</>;
}

function MapProof({model,fallback}:{model:ResolvedContactFixture;fallback:boolean}){const proof=model.proofs[0];if(fallback||model.failedProof)return <div className="xp-contact__proof-fallback" data-proof-id={proof.id} data-proof-state="fallback" role="img" aria-label={`${proof.placeLabel}. Map unavailable.`}>Route details remain available through directions.</div>;return <section className="xp-contact__map" data-proof-id={proof.id} data-runtime-proof="map-ui" aria-label={`${proof.placeLabel} schematic route map`}><div className="xp-contact__map-grid" aria-hidden="true"><i/><i/><i/><i/><i/></div><span className="xp-contact__map-node xp-contact__map-node--origin">Warehouse</span><span className="xp-contact__map-node xp-contact__map-node--hub">{proof.placeLabel}</span><span className="xp-contact__map-node xp-contact__map-node--port">Port</span><svg viewBox="0 0 100 60" aria-hidden="true"><path d="M8 45 C28 10 55 54 91 16"/><circle cx="8" cy="45" r="2"/><circle cx="51" cy="34" r="3"/><circle cx="91" cy="16" r="2"/></svg><div><strong>Three verified transfer points</strong><span>Directions remain in the contact routes.</span></div></section>}
function DashboardProof({model,fallback}:{model:ResolvedContactFixture;fallback:boolean}){const proof=model.proofs[0];if(fallback||model.failedProof)return <div className="xp-contact__proof-fallback" data-proof-id={proof.id} data-proof-state="fallback" role="img" aria-label={`${proof.title}. Dashboard unavailable.`}>Operations data is temporarily unavailable.</div>;const metrics=[["Routes live","38"],["On schedule","94%"],["Capacity open","12 lanes"]];const loads=[["North crossing","On time"],["Meridian port","Loading"],["East relay","Review"]];return <section className="xp-contact__dashboard" data-proof-id={proof.id} data-runtime-proof="dashboard-ui" aria-label={proof.title}><header><div><p>Operations / live</p><h2>{proof.title}</h2></div><span>Synced now</span></header><dl>{metrics.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><div className="xp-contact__route-chart" aria-label="Capacity by route"><span style={{"--value":"72%"} as CSSProperties}/><span style={{"--value":"48%"} as CSSProperties}/><span style={{"--value":"86%"} as CSSProperties}/><span style={{"--value":"61%"} as CSSProperties}/></div><div className="xp-contact__load-list" role="table">{loads.map(([name,state])=><div role="row" key={name}><strong role="cell">{name}</strong><span role="cell">{state}</span></div>)}</div></section>}

function Evidence({model,scenario}:{model:ResolvedContactFixture;scenario?:ContactScenario}){const projected=new Set([...model.offices.flatMap(({mediaId})=>mediaId?[mediaId]:[]),...model.clients.map(({mediaId})=>mediaId)]);return <div className="xp-contact__evidence">
  {model.media.filter(({id})=>!projected.has(id)).map((seat)=><MediaView model={model} id={seat.id} forcedFallback={scenario?.mediaFallback} key={seat.id}/>) }
  {model.clients.length?<section className="xp-contact__clients"><p>{model.clientCountLabel}</p><div>{model.clients.map((client)=><article tabIndex={0} data-client-id={client.id} key={client.id}><MediaView model={model} id={client.mediaId} forcedFallback={scenario?.mediaFallback}/><span><strong>{client.name}</strong><small>{client.role}</small></span></article>)}</div></section>:null}
  {model.testimonial?<figure className="xp-contact__testimonial"><blockquote>“{model.testimonial.quote}”</blockquote><figcaption><strong>{model.testimonial.name}</strong><span>{model.testimonial.role}</span><span aria-label={`${model.testimonial.rating} out of 5 stars`}>{"★".repeat(model.testimonial.rating)}</span></figcaption></figure>:null}
  {model.profile?<section className="xp-contact__profile"><p>{model.profile.availability}</p><h2>{model.profile.name}</h2><span>{model.profile.role}</span><div>{model.profile.socialActionIds.map((id)=><NativeAction action={findAction(model,id)} key={id}/>)}</div></section>:null}
  {model.companies.length?<div className="xp-contact__companies" data-paused={scenario?.paused?"true":undefined}>{model.companies.map((company)=><figure data-company-id={company.id} key={company.id}><VectorView model={model} id={company.vectorId} forcedFallback={scenario?.mediaFallback}/><figcaption>{company.name}</figcaption></figure>)}</div>:null}
  {model.profile?.companyVectorIds.length&&!model.companies.length?<div className="xp-contact__companies" data-paused={scenario?.paused?"true":undefined}>{model.profile.companyVectorIds.map((id)=><VectorView model={model} id={id} forcedFallback={scenario?.mediaFallback} key={id}/>)}</div>:null}
  {model.proofs[0]?.kind==="map-ui"?<MapProof model={model} fallback={Boolean(scenario?.proofFallback)}/>:null}{model.proofs[0]?.kind==="dashboard-ui"?<DashboardProof model={model} fallback={Boolean(scenario?.proofFallback)}/>:null}
  </div>}

function Intro({model,scenario}:{model:ResolvedContactFixture;scenario?:ContactScenario}){return <header className="xp-contact__intro">{model.identityLabel&&model.vectors[0]&&!model.shellLinks?<div className="xp-contact__identity"><VectorView model={model} id={model.vectors[0].id} forcedFallback={scenario?.mediaFallback}/><span>{model.identityLabel}</span></div>:null}{model.eyebrow?<p className="xp-contact__eyebrow">{model.eyebrow}</p>:null}<h1>{model.heading}</h1><p>{model.description}</p></header>}
function Methods({model}:{model:ResolvedContactFixture}){return model.methods.length?<div className="xp-contact__methods">{model.methods.map((method)=><article key={method.id}><p className="xp-contact__kicker">Contact route</p><h3>{method.label}</h3><p>{method.description}</p></article>)}</div>:null}
function Utilities({model}:{model:ResolvedContactFixture}){const used=new Set([...model.channels,...model.offices.flatMap(({channels})=>channels)].flatMap(({actionIds})=>actionIds));if(model.form)used.add(model.form.submitActionId);if(model.profile)model.profile.socialActionIds.forEach((id)=>used.add(id));if(model.shellLinks)[...model.shellLinks.topActionIds,...model.shellLinks.footerActionIds,...model.shellLinks.socialActionIds].forEach((id)=>used.add(id));const actions=model.actions.filter(({id})=>!used.has(id));return actions.length?<nav className="xp-contact__utilities" aria-label="Additional contact links">{actions.map((action)=><NativeAction action={action} key={action.id}/>)}</nav>:null}
function Shell({model,scenario,children}:{model:ResolvedContactFixture;scenario?:ContactScenario;children:ReactNode}){if(!model.shellLinks)return children;const actions=(ids:string[])=>ids.map((id)=><NativeAction action={findAction(model,id)} key={id}/>);return <div className="xp-contact__shell" data-shell-relocation-owner="marketing-shell"><header><div className="xp-contact__shell-brand"><VectorView model={model} id={model.shellLinks.identityVectorId} forcedFallback={scenario?.mediaFallback}/><strong>{model.identityLabel}</strong></div><nav aria-label="Primary">{actions(model.shellLinks.topActionIds)}</nav></header>{children}<footer><nav aria-label="Footer">{actions(model.shellLinks.footerActionIds)}</nav><nav aria-label="Social">{actions(model.shellLinks.socialActionIds)}</nav></footer></div>}

function Composition({model,scenario,deviceClass}:{model:ResolvedContactFixture;scenario?:ContactScenario;deviceClass:DeviceClass}){const form=model.form?<ContactForm model={model} scenario={scenario} deviceClass={deviceClass}/>:null;const directoryFirst=model.sourceKey==="contact-us-page-07"&&(deviceClass==="M"||deviceClass==="TP");const directory=<Directory model={model} scenario={scenario}/>;const methods=<Methods model={model}/>;const content=<><Intro model={model} scenario={scenario}/><Channels model={model}/>{directoryFirst?directory:methods}{directoryFirst?methods:directory}<Evidence model={model} scenario={scenario}/>{form}<Utilities model={model}/></>;return <Shell model={model} scenario={scenario}><div className="xp-contact__composition" data-composition={model.composition}>{content}</div></Shell>}
const renderForm=({core,deviceClass,form}:{core:{model:ResolvedContactFixture;scenario?:ContactScenario};deviceClass:DeviceClass;form:string})=><div className="xp-contact__native-form" data-native-form={form}><Composition model={core.model} scenario={core.scenario} deviceClass={deviceClass}/></div>;
const renderers={mobile:renderForm,"tablet-portrait":renderForm,"tablet-landscape":renderForm,"desktop-standard":renderForm,"desktop-wide":renderForm};

export function Contact({fixture,media,stress,scenario,className}:ContactProperties){const deviceClass=useDeviceClass();const model=resolveContactFixture(fixture,media,stress);return <section className={["xp-contact",className].filter(Boolean).join(" ")} data-xp-owner="Contact" data-contact-state-owner data-source-key={model.sourceKey} data-preset={model.preset} data-composition={model.composition} data-device-class={deviceClass} data-stress={stress}><MorphSlot className="xp-contact__morph" ladder={ladder} core={{model,scenario}} renderers={renderers}/></section>}
