import { resolveCategoryMedia, type CategoryAction, type CategoryDeviceForm, type CategoryMediaRef, type ProductCategoryMediaMap, type ProductCategoryStressKey, type ResolvedCategoryMedia } from "./category-nav-model";

export type HotspotCropKey=CategoryDeviceForm|`DW-slot-${240|320|420|560|720|960}`;
export type HotspotProduct={id:string;name:string;mediaId:string;price:{currency:"USD";amount:number};rating:{value:number;maximum:5;reviewCount:number};description:string;action:CategoryAction&{kind:"destination"}};
export type HotspotAnchor={hotspotId:string;productId:string;byCrop?:Partial<Record<HotspotCropKey,{xPct:number;yPct:number}>>};
type HotspotTextPatch={targetType:"intro"|"product"|"action"|"media"|"labels";targetId:string;field:string;value:string};
export type HotspotStageFixture={schemaVersion:number;id:"product-category-13";sourceKey:"product-category-13";owner:"HotspotStage";preset:"room-hotspots";heading:string;description:string;roomMedia:CategoryMediaRef&{role:"editorial-photo"};products:HotspotProduct[];hotspots:HotspotAnchor[];initialHotspotId:string;labels:{selectProduct:string;save:string;unsave:string;quantity:string;decrease:string;increase:string;dismiss:string};stress:{short:{textPatches:HotspotTextPatch[]};longLocale:{textPatches:HotspotTextPatch[];direction?:"rtl"};error:{roomFailureMessage:string;productFailureMessage:string;mediaFailureMessage:string;referenceFailureMessage:string;failMediaIds:string[]}}};
export type ResolvedHotspotStage=Omit<HotspotStageFixture,"stress">&{activeStress?:ProductCategoryStressKey;direction?:"rtl";room:ResolvedCategoryMedia;productMedia:Map<string,ResolvedCategoryMedia>;messages:{roomFailure:string;productFailure:string;mediaFailure:string;referenceFailure:string};terminalEligible:boolean};

const required=(value:unknown,label:string)=>{if(typeof value!=="string"||!value.trim())throw new Error(`product-category-13 requires ${label}.`)};
function applyPatches(fixture:HotspotStageFixture,patches:HotspotTextPatch[]){const output=structuredClone(fixture);for(const patch of patches){let target:Record<string,unknown>|undefined;if(patch.targetType==="intro")target=output as unknown as Record<string,unknown>;else if(patch.targetType==="labels")target=output.labels;else if(patch.targetType==="product")target=output.products.find(({id})=>id===patch.targetId) as unknown as Record<string,unknown>;else if(patch.targetType==="action")target=output.products.find(({action})=>action.id===patch.targetId)?.action as unknown as Record<string,unknown>;else if(patch.targetType==="media"&&patch.targetId===output.roomMedia.id)target=output.roomMedia as unknown as Record<string,unknown>;if(!target||!(patch.field in target))throw new Error(`product-category-13 stress references unknown ${patch.targetType}/${patch.targetId}/${patch.field}.`);target[patch.field]=patch.value}return output}

export function resolveHotspotStageFixture(fixture:HotspotStageFixture,map:ProductCategoryMediaMap,stress?:ProductCategoryStressKey):ResolvedHotspotStage{
  const copyStress=stress==="short"||stress==="longLocale"?stress:undefined;const active=copyStress?applyPatches(fixture,fixture.stress[copyStress].textPatches):structuredClone(fixture);
  if(active.owner!=="HotspotStage"||active.preset!=="room-hotspots"||active.products.length!==4||active.hotspots.length!==4)throw new Error("product-category-13 is outside the closed HotspotStage contract.");
  required(active.heading,"heading");required(active.description,"description");
  if(new Set(active.products.map(({id})=>id)).size!==4||new Set(active.hotspots.map(({hotspotId})=>hotspotId)).size!==4)throw new Error("product-category-13 repeats product or hotspot identity.");
  for(const product of active.products){required(product.name,`${product.id} name`);required(product.description,`${product.id} description`);required(product.action.label,`${product.id} action`);if(!product.action.href.startsWith("/demo/")||product.action.href.includes("//"))throw new Error(`${product.id} requires a local /demo route.`);if(product.price.amount<0||product.rating.value<0||product.rating.value>5||product.rating.reviewCount<0)throw new Error(`${product.id} has invalid numeric evidence.`)}
  for(const hotspot of active.hotspots)if(!active.products.some(({id})=>id===hotspot.productId))throw new Error(`${hotspot.hotspotId} has a dangling product.`);
  if(!active.hotspots.some(({hotspotId})=>hotspotId===active.initialHotspotId))throw new Error("product-category-13 initialHotspotId is unresolved.");
  const roomPlacement=map.placements.find(({slug,seatId})=>slug===active.sourceKey&&seatId===active.roomMedia.id);if(!roomPlacement)throw new Error("product-category-13 room placement is unaudited.");
  if(roomPlacement.status==="resolved")for(const hotspot of active.hotspots){const keys=Object.keys(hotspot.byCrop??{});if(keys.length!==11)throw new Error(`${hotspot.hotspotId} requires eleven measured crop anchors.`);for(const point of Object.values(hotspot.byCrop??{}))if(!point||point.xPct<0||point.xPct>100||point.yPct<0||point.yPct>100)throw new Error(`${hotspot.hotspotId} has an invalid crop-relative anchor.`)}
  const failureIds=new Set(stress==="error"?active.stress.error.failMediaIds:stress==="roomMediaFallback"?[active.roomMedia.id]:stress==="productMediaFallback"?[active.products[0].mediaId]:[]);
  const room=resolveCategoryMedia(map,active.sourceKey,active.roomMedia,"M",failureIds.has(active.roomMedia.id));
  const productMedia=new Map(active.products.map((product)=>{const seat:CategoryMediaRef={id:product.mediaId,alt:product.name,role:"product-still",aspect:"1:1"};return [product.mediaId,resolveCategoryMedia(map,active.sourceKey,seat,"M",failureIds.has(product.mediaId))]}));
  const terminalEligible=room.status==="resolved"&&[...productMedia.values()].every(({status})=>status==="resolved");
  const {stress:_,...core}=active;return {...core,activeStress:stress,direction:stress==="longLocale"?"rtl":undefined,room,productMedia,messages:{roomFailure:active.stress.error.roomFailureMessage,productFailure:active.stress.error.productFailureMessage,mediaFailure:active.stress.error.mediaFailureMessage,referenceFailure:active.stress.error.referenceFailureMessage},terminalEligible};
}
