"use client";

import { AdaptiveOverlay, type DeviceClass } from "@xp/primitives";
import type { ReactNode } from "react";
import { AppBarActionControl, AppBarSearchControl, partitionCompactAppBarActions, type AppBarModel, type AppBarProperties } from "./app-bar";
import { destinationsByPriority, type NavChild, type NavDestination, type NavIconRenderer, type NavModel } from "./nav-model";

export type AnalyticsUpsell = { eyebrow: string; headline: string; body: string; cta: string; actionId: string };
export type AnalyticsUpsellFooterLink = { id: string; label: string; href: string };
export type AnalyticsUpsellModel = { upsell: AnalyticsUpsell; footerLinks: readonly AnalyticsUpsellFooterLink[] };
export type AnalyticsUpsellReachability = { id: string; kind: "destination" | "action" | "upsell"; parentId?: string; surface: "compact-sheet" | "analytics-navigation" | "app-bar" | "upsell-card" };

export function analyticsUpsellReachability(nav: NavModel, appBar: AppBarModel, model: AnalyticsUpsellModel, deviceClass: DeviceClass): AnalyticsUpsellReachability[] {
  const compact = deviceClass === "M" || deviceClass === "TP";
  return [...destinationsByPriority(nav).flatMap((destination): AnalyticsUpsellReachability[] => [{ id: destination.id, kind: "destination", surface: compact ? "compact-sheet" : "analytics-navigation" }, ...(destination.children ?? []).map(({ id }) => ({ id, kind: "destination" as const, parentId: destination.id, surface: compact ? "compact-sheet" as const : "analytics-navigation" as const }))]), ...(appBar.actions ?? []).map(({ id }) => ({ id, kind: "action" as const, surface: "app-bar" as const })), { id: model.upsell.actionId, kind: "upsell", surface: compact ? "compact-sheet" : "upsell-card" }];
}

function Icon({ destination, renderIcon }: { destination: NavDestination; renderIcon?: NavIconRenderer }) { return <span className="xp-shell-nav__icon" data-icon-key={destination.icon} aria-hidden="true">{renderIcon?.(destination.icon, destination) ?? destination.icon.slice(0, 1).toUpperCase()}</span>; }
function Child({ child, parentId, activeId }: { child: NavChild; parentId: string; activeId: string }) { return <a className="xp-analytics-upsell__child" href={child.href} data-nav-id={child.id} data-nav-parent-id={parentId} aria-current={child.id === activeId ? "page" : undefined}>{child.label}</a>; }
function Link({ destination, activeId, renderIcon }: { destination: NavDestination; activeId: string; renderIcon?: NavIconRenderer }) { return <a className="xp-analytics-upsell__destination" href={destination.href} data-nav-id={destination.id} aria-current={destination.id === activeId ? "page" : undefined} aria-label={destination.label}><Icon destination={destination} renderIcon={renderIcon} /><span>{destination.label}</span>{destination.badge ? <span className="xp-shell-badge" aria-label={`${destination.badge.label}: ${destination.badge.value}`}>{destination.badge.value}</span> : null}</a>; }
function Branch({ destination, activeId, renderIcon, rail }: { destination: NavDestination; activeId: string; renderIcon?: NavIconRenderer; rail: boolean }) {
  if (rail) return <AdaptiveOverlay intent="menu" presentation={{ TL: "popover" }} why="Landscape tablet analytics children open beside the label-free rail."><AdaptiveOverlay.Trigger className="xp-analytics-upsell__destination" aria-label={`Open ${destination.label}`} data-nav-id={destination.id} data-xp-analytics-branch-trigger=""><Icon destination={destination} renderIcon={renderIcon} /><span>{destination.label}</span></AdaptiveOverlay.Trigger><AdaptiveOverlay.Content data-xp-analytics-branch-overlay="" data-branch-id={destination.id}><AdaptiveOverlay.Header title={destination.label} description={`Choose a ${destination.label} report.`} /><AdaptiveOverlay.Body><ul className="xp-analytics-upsell__children">{destination.children?.map((child) => <li key={child.id}><Child child={child} parentId={destination.id} activeId={activeId} /></li>)}</ul></AdaptiveOverlay.Body><AdaptiveOverlay.Footer><AdaptiveOverlay.Close>Close {destination.label}</AdaptiveOverlay.Close></AdaptiveOverlay.Footer></AdaptiveOverlay.Content></AdaptiveOverlay>;
  return <details className="xp-analytics-upsell__branch" open={destination.children?.some(({ id }) => id === activeId)} data-xp-nav-branch=""><summary className="xp-analytics-upsell__destination" data-nav-id={destination.id} aria-current={destination.id === activeId ? "page" : undefined}><Icon destination={destination} renderIcon={renderIcon} /><span>{destination.label}</span><span className="xp-analytics-upsell__chevron" aria-hidden="true">⌄</span></summary><ul className="xp-analytics-upsell__children">{destination.children?.map((child) => <li key={child.id}><Child child={child} parentId={destination.id} activeId={activeId} /></li>)}</ul></details>;
}
function Navigation({ nav, activeId, renderIcon, rail = false }: { nav: NavModel; activeId: string; renderIcon?: NavIconRenderer; rail?: boolean }) {
  const destinations = destinationsByPriority(nav); const byId = new Map(destinations.map((destination) => [destination.id, destination])); const grouped = new Set((nav.groups ?? []).flatMap(({ destinationIds }) => [...destinationIds]));
  const groups = [...(nav.groups ?? []).map((group) => ({ id: group.id, label: group.label, items: group.destinationIds.map((id) => byId.get(id)).filter((item): item is NavDestination => Boolean(item)) })), { id: "other", label: "More", items: destinations.filter(({ id }) => !grouped.has(id)) }].filter(({ items }) => items.length);
  return <nav className="xp-analytics-upsell__navigation" aria-label="Analytics navigation" data-xp-analytics-navigation="" data-nav-presentation={rail ? "rail" : "panel"}>{groups.map((group) => <section key={group.id} aria-labelledby={`xp-analytics-group-${group.id}`}><h2 id={`xp-analytics-group-${group.id}`}>{group.label}</h2><ul>{group.items.map((destination) => <li key={destination.id}>{destination.children?.length ? <Branch destination={destination} activeId={activeId} renderIcon={renderIcon} rail={rail} /> : <Link destination={destination} activeId={activeId} renderIcon={renderIcon} />}</li>)}</ul></section>)}</nav>;
}
function Upsell({ model, compact = false, onAction }: { model: AnalyticsUpsell; compact?: boolean; onAction?: AppBarProperties["onAction"] }) { return <aside className="xp-analytics-upsell__card" data-xp-analytics-upsell="" data-upsell-presentation={compact ? "compact" : "card"} aria-labelledby="xp-analytics-upsell-title"><span>{model.eyebrow}</span><h2 id="xp-analytics-upsell-title">{model.headline}</h2><p>{model.body}</p><button type="button" data-xp-analytics-upsell-action="" data-action-id={model.actionId} onClick={() => onAction?.(model.actionId)}>{model.cta}</button></aside>; }
function Sidebar({ nav, model, activeId, renderIcon, onAction, rail = false }: { nav: NavModel; model: AnalyticsUpsellModel; activeId: string; renderIcon?: NavIconRenderer; onAction?: AppBarProperties["onAction"]; rail?: boolean }) { return <><a className="xp-analytics-upsell__brand" href="#xp-shell-content"><span aria-hidden="true">{nav.identity.shortLabel}</span><strong>{nav.identity.label}</strong></a><Navigation nav={nav} activeId={activeId} renderIcon={renderIcon} rail={rail} /><Upsell model={model.upsell} compact={rail} onAction={onAction} /></>; }
function NavOverlay({ nav, model, activeId, deviceClass, renderIcon, onAction }: { nav: NavModel; model: AnalyticsUpsellModel; activeId: string; deviceClass: "M" | "TP"; renderIcon?: NavIconRenderer; onAction?: AppBarProperties["onAction"] }) { return <AdaptiveOverlay intent="menu" presentation={{ M: "action-sheet", TP: "action-sheet" }} why="Full analytics navigation and premium context share one scroll-safe sheet with persistent Close."><AdaptiveOverlay.Trigger className="xp-analytics-upsell__overlay-trigger" aria-label="Open analytics navigation" data-xp-analytics-overlay-trigger="" data-xp-nav-renderer=""><span aria-hidden="true">◧</span></AdaptiveOverlay.Trigger><AdaptiveOverlay.Content data-xp-analytics-overlay=""><AdaptiveOverlay.Header title={nav.identity.label} description="Analytics reports and historical data options." /><AdaptiveOverlay.Body><Sidebar nav={nav} model={model} activeId={activeId} renderIcon={renderIcon} onAction={onAction} /></AdaptiveOverlay.Body><AdaptiveOverlay.Footer><AdaptiveOverlay.Close>Close navigation</AdaptiveOverlay.Close></AdaptiveOverlay.Footer></AdaptiveOverlay.Content></AdaptiveOverlay>; }
function CompactActions({ actions, deviceClass, renderActionIcon, onAction }: { actions: NonNullable<AppBarModel["actions"]>; deviceClass: "M" | "TP"; renderActionIcon?: AppBarProperties["renderActionIcon"]; onAction?: AppBarProperties["onAction"] }) {
  const { visible, overflow } = partitionCompactAppBarActions(actions, deviceClass);
  return <div className="xp-analytics-upsell__compact-actions">{visible.map((action) => <AppBarActionControl key={action.id} action={action} renderIcon={renderActionIcon} onAction={onAction} />)}<AdaptiveOverlay intent="menu" presentation={{ M: "action-sheet", TP: "action-sheet" }} why="All compact app actions remain reachable through the familiar More actions sheet."><AdaptiveOverlay.Trigger aria-label="More actions"><span aria-hidden="true">•••</span></AdaptiveOverlay.Trigger><AdaptiveOverlay.Content data-xp-analytics-actions-overlay=""><AdaptiveOverlay.Header title="More actions" description="Analytics actions that do not fit the compact app bar." /><AdaptiveOverlay.Body data-xp-analytics-actions-scroll="" data-xp-scroll=""><ul>{overflow.map((action) => <li key={action.id}><AppBarActionControl action={action} renderIcon={renderActionIcon} onAction={onAction} /></li>)}</ul></AdaptiveOverlay.Body><AdaptiveOverlay.Footer data-xp-analytics-actions-footer=""><AdaptiveOverlay.Close>Close actions</AdaptiveOverlay.Close></AdaptiveOverlay.Footer></AdaptiveOverlay.Content></AdaptiveOverlay></div>;
}
function AppBar({ nav, appBar, model, activeId, deviceClass, renderIcon, renderActionIcon, onAction }: { nav: NavModel; appBar: AppBarModel; model: AnalyticsUpsellModel; activeId: string; deviceClass: DeviceClass; renderIcon?: NavIconRenderer; renderActionIcon?: AppBarProperties["renderActionIcon"]; onAction?: AppBarProperties["onAction"] }) {
  const compact = deviceClass === "M" || deviceClass === "TP"; const actions = [...(appBar.actions ?? [])].sort((a, b) => a.priority - b.priority);
  return <header className="xp-analytics-upsell__app-bar" data-xp-region="top">{compact ? <NavOverlay nav={nav} model={model} activeId={activeId} deviceClass={deviceClass} renderIcon={renderIcon} onAction={onAction} /> : <span className="xp-analytics-upsell__context">{appBar.context.title}</span>}{appBar.search ? <AppBarSearchControl search={appBar.search} deviceClass={deviceClass} inline={!compact && deviceClass !== "TL"} /> : null}{compact ? <CompactActions actions={actions} deviceClass={deviceClass} renderActionIcon={renderActionIcon} onAction={onAction} /> : <div className="xp-analytics-upsell__actions">{actions.map((action) => <AppBarActionControl key={action.id} action={action} renderIcon={renderActionIcon} onAction={onAction} />)}</div>}</header>;
}
export function AnalyticsUpsellShell({ nav, appBar, model, activeId, deviceClass, children, renderIcon, renderActionIcon, onAction, sourceSlug, sourcePreset }: { nav: NavModel; appBar: AppBarModel; model: AnalyticsUpsellModel; activeId: string; deviceClass: DeviceClass; children: ReactNode; renderIcon?: NavIconRenderer; renderActionIcon?: AppBarProperties["renderActionIcon"]; onAction?: AppBarProperties["onAction"]; sourceSlug?: string; sourcePreset?: string }) {
  const compact = deviceClass === "M" || deviceClass === "TP";
  return <div className="xp-app-shell xp-analytics-upsell-shell" data-xp-shell="" data-xp-analytics-upsell-shell="" data-shell-family="app" data-device-class={deviceClass} data-variant="analytics-inset" data-shell-anatomy="app.inset.analytics-upsell" data-skin="inset" data-nav-placement="side" data-source-slug={sourceSlug} data-source-preset={sourcePreset}><a className="xp-shell-skip" href="#xp-shell-content">Skip to content</a>{compact ? <AppBar nav={nav} appBar={appBar} model={model} activeId={activeId} deviceClass={deviceClass} renderIcon={renderIcon} renderActionIcon={renderActionIcon} onAction={onAction} /> : null}<div className="xp-analytics-upsell__body">{!compact ? <aside className="xp-analytics-upsell__sidebar" data-xp-nav-renderer="" data-xp-region="navigation"><Sidebar nav={nav} model={model} activeId={activeId} renderIcon={renderIcon} onAction={onAction} rail={deviceClass === "TL"} /></aside> : null}<div className="xp-analytics-upsell__stage">{!compact ? <AppBar nav={nav} appBar={appBar} model={model} activeId={activeId} deviceClass={deviceClass} renderIcon={renderIcon} renderActionIcon={renderActionIcon} onAction={onAction} /> : null}<main className="xp-analytics-upsell__main xp-slot" id="xp-shell-content" tabIndex={-1} data-xp-region="content"><section className="xp-analytics-upsell__surface" data-xp-analytics-work-surface="">{children}</section></main></div></div><footer className="xp-analytics-upsell__footer" data-xp-region="bottom"><nav aria-label="Analytics resources"><ul>{model.footerLinks.map((link) => <li key={link.id}><a href={link.href} data-xp-footer-link-id={link.id}>{link.label}</a></li>)}</ul></nav></footer></div>;
}
