"use client";

import { Field, StickyActionBar, useDeviceClass, type DeviceClass } from "@xp/primitives";
import { useEffect, useMemo, useReducer, useRef, useState, type FormEvent } from "react";
import { AuthShell, type AuthShellScenario } from "./auth-shell";
import type { ResolvedAuthShellModel } from "./auth-model";
import type { ResolvedResetField, ResolvedResetFixture } from "./reset-model";

export const resetHostForms:Record<DeviceClass,"focused-screen"|"portrait-card"|"compact-split"|"balanced-split"|"wide-guided-split">={
  M:"focused-screen",TP:"portrait-card",TL:"compact-split",DS:"balanced-split",DW:"wide-guided-split",
};
export type ResetPhase="form"|"invalid"|"pending"|"done"|"token-expired"|"error";
export type ResetValues={email:string;password:string;confirm:string};
export type ResetValidity={length:boolean;case:boolean;number:boolean;symbol:boolean;match:boolean};
export type ResetRuntimeState={phase:ResetPhase;values:ResetValues;visible:{password:boolean;confirm:boolean};touched:Set<keyof ResetValues>;announcement:string};
export type ResetScenario={phase?:ResetPhase;email?:string;password?:string;confirm?:string;invalid?:ResolvedResetField["id"];rulesOpen?:boolean;mediaFallback?:boolean;reducedData?:boolean};
export type ResetUnitProperties={model:ResolvedResetFixture;shellModel:ResolvedAuthShellModel;deviceClass?:DeviceClass;scenario?:ResetScenario;shellScenario?:AuthShellScenario;onReset?:(values:ResetValues)=>"done"|"error"|Promise<"done"|"error">;onBackToLogin?:()=>void};

const EMAIL=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
export function resetValidity(values:ResetValues):ResetValidity{return {length:[...values.password].length>=12,case:/[A-Z]/u.test(values.password),number:/\d/u.test(values.password),symbol:/[^\p{L}\p{N}\s]/u.test(values.password),match:Boolean(values.password)&&values.password===values.confirm};}
export function resetStrength(validity:ResetValidity){return [validity.length,validity.case,validity.number,validity.symbol].filter(Boolean).length;}
export function resetFieldError(model:ResolvedResetFixture,field:ResolvedResetField,state:ResetRuntimeState){const value=state.values[field.id];if(!state.touched.has(field.id)&&state.phase!=="invalid")return undefined;if(!value.trim())return field.requiredError;const validity=resetValidity(state.values);if(field.id==="email"&&!EMAIL.test(value))return field.invalidError;if(field.id==="password"&&(!validity.length||!validity.case||!validity.number||!validity.symbol))return field.invalidError;if(field.id==="confirm"&&!validity.match)return field.invalidError;return undefined;}

export function createResetState(model:ResolvedResetFixture,scenario?:ResetScenario):ResetRuntimeState{
  const values={email:scenario?.email??"",password:scenario?.password??"",confirm:scenario?.confirm??""};const touched=new Set<keyof ResetValues>();if(scenario?.invalid)touched.add(scenario.invalid);
  const phase=scenario?.invalid?"invalid":scenario?.phase??"form";
  return {phase,values,visible:{password:false,confirm:false},touched,announcement:phase==="pending"?model.labels.pendingAnnouncement:phase==="done"?model.labels.doneBody:phase==="token-expired"?model.labels.expiredBody:""};
}
type Event={type:"change";field:keyof ResetValues;value:string}|{type:"blur";field:keyof ResetValues}|{type:"toggle";field:"password"|"confirm"}|{type:"submit"}|{type:"resolved";result:"done"|"error"};
export function reduceResetState(state:ResetRuntimeState,event:Event,model:ResolvedResetFixture):ResetRuntimeState{
  if(event.type==="change"){if(state.phase==="pending")return state;return {...state,phase:state.phase==="invalid"||state.phase==="error"?"form":state.phase,values:{...state.values,[event.field]:event.value},announcement:""};}
  if(event.type==="blur"){if(state.phase==="pending")return state;const touched=new Set(state.touched);touched.add(event.field);return {...state,touched};}
  if(event.type==="toggle"){if(state.phase==="pending")return state;return {...state,visible:{...state.visible,[event.field]:!state.visible[event.field]}};}
  if(event.type==="submit"){if(state.phase==="pending"||state.phase==="done"||state.phase==="token-expired")return state;const touched=new Set<keyof ResetValues>(model.fields.map(x=>x.id));const invalid=model.fields.some(field=>resetFieldError(model,field,{...state,touched,phase:"invalid"}));return invalid?{...state,touched,phase:"invalid",announcement:""}:{...state,touched,phase:"pending",announcement:model.labels.pendingAnnouncement};}
  if(state.phase!=="pending")return state;return event.result==="done"?{...state,phase:"done",announcement:model.labels.doneBody}:{...state,phase:"error",announcement:model.labels.fallbackBody};
}

function useResetTextScale(){const [scale,setScale]=useState<"normal"|"extreme">("normal");useEffect(()=>{const root=document.documentElement,read=()=>setScale(parseFloat(getComputedStyle(root).fontSize)>=48?"extreme":"normal");read();const observer=new MutationObserver(read);observer.observe(root,{attributes:true,attributeFilter:["class","style"]});return()=>observer.disconnect();},[]);return scale;}

function RuleList({model,validity,compact,initialOpen=false}:{model:ResolvedResetFixture;validity:ResetValidity;compact:boolean;initialOpen?:boolean}){
  const [open,setOpen]=useState(initialOpen);const rows=<ul className="xp-reset__rules" aria-label={model.labels.rulesOpen}>{model.rules.map(rule=><li key={rule.id} data-rule-id={rule.id} data-state={validity[rule.id]?"pass":"open"}><span aria-hidden="true">{validity[rule.id]?"✓":"○"}</span><span>{rule.label}</span></li>)}<li data-rule-id="match" data-state={validity.match?"pass":"open"}><span aria-hidden="true">{validity.match?"✓":"○"}</span><span>{model.labels.match}</span></li></ul>;
  if(!compact)return <section className="xp-reset__guidance" data-reset-guidance=""><h2>{model.labels.rulesOpen}</h2>{rows}</section>;
  return <details className="xp-reset__rules-disclosure" open={open} onToggle={event=>setOpen(event.currentTarget.open)}><summary>{open?model.labels.rulesClose:model.labels.rulesOpen}</summary>{rows}</details>;
}

function ResetField({model,field,state,dispatch}:{model:ResolvedResetFixture;field:ResolvedResetField;state:ResetRuntimeState;dispatch:(event:Event)=>void}){
  const error=resetFieldError(model,field,state),password=field.type==="password",visible=password?state.visible[field.id as "password"|"confirm"]:false,revealLabel=visible?model.labels.revealHide:model.labels.revealShow,expandedCopy=model.activeStress==="longLocale";
  return <Field id={`${model.sourceKey}-${field.id}`} invalid={Boolean(error)} hasHelp={expandedCopy} hasError={Boolean(error)}><Field.Label>{field.label}</Field.Label>{expandedCopy?<Field.Help className="xp-reset__field-example">{field.placeholder}</Field.Help>:null}<div className="xp-reset__field-control" data-copy-pressure={password&&expandedCopy?"expanded":undefined}><Field.Input name={field.name} type={password&&visible?"text":field.type} inputMode={field.inputMode??"text"} enterKeyHint={field.enterKeyHint} autoComplete={field.autoComplete} autoCapitalize={field.autoCapitalize} spellCheck={field.spellCheck} required={field.required} placeholder={expandedCopy?undefined:field.placeholder} disabled={state.phase==="pending"} value={state.values[field.id]} onChange={event=>dispatch({type:"change",field:field.id,value:event.currentTarget.value})} onBlur={()=>dispatch({type:"blur",field:field.id})}/>{password?<button className="xp-reset__reveal" type="button" aria-label={revealLabel} aria-pressed={visible} disabled={state.phase==="pending"} onClick={()=>dispatch({type:"toggle",field:field.id as "password"|"confirm"})}><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"/><circle cx="12" cy="12" r="2.75"/>{visible?<path d="m4.5 4.5 15 15"/>:null}</svg><span aria-hidden="true">{revealLabel}</span></button>:null}</div>{error?<Field.Error>{error}</Field.Error>:null}</Field>;
}

export function ResetUnit({model,shellModel,deviceClass:explicitClass,scenario,shellScenario,onReset,onBackToLogin}:ResetUnitProperties){
  const contextClass=useDeviceClass(),deviceClass=explicitClass??contextClass,textScale=useResetTextScale();const [state,dispatch]=useReducer((current:ResetRuntimeState,event:Event)=>reduceResetState(current,event,model),undefined,()=>createResetState(model,scenario));const formRef=useRef<HTMLFormElement>(null),validity=useMemo(()=>resetValidity(state.values),[state.values]),strength=resetStrength(validity),strengthLabel=strength===0?model.labels.strengthEmpty:strength<2?model.labels.strengthWeak:strength<4?model.labels.strengthFair:model.labels.strengthStrong,wideGuidance=deviceClass==="DW"&&Boolean(shellModel.proof),compactGuidance=deviceClass==="M"||deviceClass==="TP"||deviceClass==="TL",formId=`${model.sourceKey}-reset-form`;
  useEffect(()=>{if(state.phase==="invalid")formRef.current?.querySelector<HTMLElement>('[aria-invalid="true"]')?.focus();},[state.phase]);
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(state.phase==="pending")return;const touched=new Set<keyof ResetValues>(model.fields.map(x=>x.id));const invalid=model.fields.some(field=>resetFieldError(model,field,{...state,touched,phase:"invalid"}));dispatch({type:"submit"});if(invalid)return;try{const result=await(onReset?.(state.values)??Promise.resolve("done" as const));dispatch({type:"resolved",result});}catch{dispatch({type:"resolved",result:"error"});}};
  const guidance=<RuleList model={model} validity={validity} compact={compactGuidance&&!wideGuidance} initialOpen={Boolean(scenario?.rulesOpen)||state.phase==="invalid"}/>;
  const body=state.phase==="token-expired"?<section className="xp-reset__result" data-reset-result="expired"><h2>{model.labels.expiredHeading}</h2><p>{model.labels.expiredBody}</p><a href={model.expiredAction.href}>{model.expiredAction.label}</a></section>:state.phase==="done"?<section className="xp-reset__result" data-reset-result="done"><h2>{model.labels.doneHeading}</h2><p>{model.labels.doneBody}</p><a href={model.doneAction.href}>{model.doneAction.label}</a></section>:<><form ref={formRef} id={formId} action={model.submit.action} method="post" noValidate aria-label={model.labels.formAria} aria-busy={state.phase==="pending"||undefined} data-reset-form-owner="" onSubmit={submit}><input type="hidden" name="sourceKey" value={model.sourceKey}/>{model.fields.map(field=><ResetField key={field.id} model={model} field={field} state={state} dispatch={dispatch}/>)}<div className="xp-reset__strength" data-strength={strength}><span>{strengthLabel}</span><progress max="4" value={strength} aria-label={strengthLabel}/></div>{wideGuidance?null:guidance}{state.phase==="error"?<p className="xp-reset__service-error" role="alert">{model.labels.fallbackBody}</p>:null}</form><StickyActionBar className="xp-reset__submit" placement="local" primary={<button type="submit" form={formId} disabled={state.phase==="pending"}>{state.phase==="pending"?model.labels.pending:model.submit.label}</button>}/><p className="xp-reset__back">{onBackToLogin?<button type="button" onClick={onBackToLogin}>{model.backToLogin.label}</button>:<a href={model.backToLogin.href}>{model.backToLogin.label}</a>}</p></>;
  return <section className="xp-reset-unit" data-xp-owner="ResetUnit" data-source-key={model.sourceKey} data-device-class={deviceClass} data-reset-form={resetHostForms[deviceClass]} data-reset-state={state.phase} data-media-status={model.mediaStatus} data-text-scale={textScale}><AuthShell model={shellModel} deviceClass={deviceClass} scenario={{...shellScenario,mediaFallback:scenario?.mediaFallback??shellScenario?.mediaFallback,reducedData:scenario?.reducedData??shellScenario?.reducedData}} reassurance={wideGuidance?guidance:undefined}><div className="xp-reset__surface">{body}<p className="xp-reset__announcement" role="status" aria-live="polite">{state.announcement}</p></div></AuthShell></section>;
}
